kit:
  name: "Cloudera Hadoop"
  link: https://github.com/qubell-bazaar/component-hadoop
  applications:
    - name: "CD Hadoop"
      manifest: https://raw.github.com/qubell-bazaar/component-hadoop/v0.1.0/component-hadoop.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * CloudServers account;
        * Ports 7180, 60010, 50030, 50070, 8888 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
